import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  imports: [],
  templateUrl: './home.html',
  styleUrl: './home.css',
})
export class Home {
  data = [
    {
      id: 1234,
      name: 'Ahmed Abdelrahman',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1258,
      name: 'ibrahim jggytyo',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 2158,
      name: 'Saad Hany',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1032,
      name: 'Ali Mahmoud',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 1548,
      name: 'SXami Abdelrahman',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    {
      id: 2145,
      name: 'Ahmed Sami',
      Year: 2023,
      Month: 'January',
      Day: 1,
      checkIn: '09:00',
      checkOut: '17:30',
      attendance: 'Present',
    },
    ]
}
